### PR TITLE
Remove the random lines on B1 and A2

### PR DESCRIPTION
**Pull request by DanielBailey-web**
Removing the lines, I didn't know how to use the divide api... So I switched it to borders
Here is a preview:
<a href="https://play.tailwindcss.com/dSxubYgrJD">Tailwind Play</a>

### CODE REVIEW

**Comment by mnaderian** [comment]
Thank you @DanielBailey-web for your kind PR. But in the older version of this component before upgrading to Tailwind 2.2 I used the borders too. Which introduced one bug! which you can see when you shrink it to a smaller screen size.

Divides solved that bug and they are truly interesting and easy to use. I suggest you read about them because I'm sure you will like them just like I did: https://tailwindcss.com/docs/divide-width

**Comment by DanielBailey-web** [comment]
@mnaderian  Are you talking about the borders being in incorrect spots on smaller screens? That's quite an easy fix... just need to add media queries. 

if that is not it, what is the bug?

Your current version using the divides has bugs also (B1 and A2 have extra lines)

I would not mind updating this PR to fix the mobile bugs. (here is it working with media queries in <a href="https://play.tailwindcss.com/BHV1YlVdcm">Tailwind Play</a>)

**Comment by mnaderian** [comment]
@DanielBailey-web Can you elaborate on the divides bug, please?
And of course a fix PR based on your idea is welcome.

**Comment by DanielBailey-web** [comment]
I believe the lines on the top right and the bottom left are bugs? are they not?
https://play.tailwindcss.com/zXPgqP6EBY
Screenshot from 2021-09-25 10-23-48

**Pull request merged**
